// ============================================================
// Research Module Catalog
// The institutional library of selectable research modules.
// Grouped by category to reflect the multidisciplinary nature
// of pharmaceutical / natural-product research.
// ============================================================

const CATALOG = [
  // ---------- Sample Preparation ----------
  { name: 'Plant Collection', category: 'Sample Preparation', icon: 'leaf', est_days: 7,
    description: 'Field collection of medicinal plant material with GPS, season and habitat documentation.',
    protocols: ['Collection site documentation', 'Voucher specimen preparation'],
    deliverables: ['Collection record sheet', 'Field photographs', 'Sample log'] },
  { name: 'Botanical Authentication', category: 'Sample Preparation', icon: 'leaf', est_days: 10,
    description: 'Taxonomic identification and voucher specimen deposition at a recognised herbarium.',
    protocols: ['Herbarium comparison', 'Expert taxonomic verification'],
    deliverables: ['Authentication certificate', 'Voucher number'] },
  { name: 'Drying and Powder Preparation', category: 'Sample Preparation', icon: 'flask', est_days: 14,
    description: 'Shade/oven drying, grinding and sieving to obtain uniform plant powder.',
    protocols: ['Shade drying SOP', 'Grinding & sieving'],
    deliverables: ['Powder yield record', 'Moisture content data'] },
  { name: 'Extraction', category: 'Sample Preparation', icon: 'beaker', est_days: 21,
    description: 'Solvent extraction (maceration / Soxhlet / ultrasonication) to obtain crude extract.',
    protocols: ['Maceration protocol', 'Soxhlet extraction', 'Solvent recovery'],
    deliverables: ['Extract yield (%)', 'Extraction log', 'Stored extract inventory'] },
  { name: 'Fractionation', category: 'Sample Preparation', icon: 'beaker', est_days: 21,
    description: 'Liquid–liquid / column fractionation into solvent fractions of increasing polarity.',
    protocols: ['Liquid-liquid partition', 'Vacuum liquid chromatography'],
    deliverables: ['Fraction yield table', 'TLC profiles'] },
  { name: 'Isolation', category: 'Sample Preparation', icon: 'beaker', est_days: 30,
    description: 'Chromatographic isolation of individual phytoconstituents.',
    protocols: ['Column chromatography', 'Preparative TLC'],
    deliverables: ['Isolated compound log', 'Purity assessment'] },
  { name: 'Purification', category: 'Sample Preparation', icon: 'beaker', est_days: 21,
    description: 'Recrystallisation / preparative HPLC purification of isolated compounds.',
    protocols: ['Recrystallisation', 'Prep-HPLC purification'],
    deliverables: ['Purity report', 'Purified compound record'] },

  // ---------- Phytochemical & Analytical ----------
  { name: 'Phytochemical Screening', category: 'Phytochemical & Analytical', icon: 'microscope', est_days: 10,
    description: 'Qualitative tests for alkaloids, flavonoids, tannins, saponins, terpenoids, glycosides.',
    protocols: ['Standard qualitative tests'],
    deliverables: ['Phytochemical screening table'] },
  { name: 'Total Phenolic Content', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 7,
    description: 'Folin–Ciocalteu assay expressed as GAE.',
    protocols: ['Folin-Ciocalteu method', 'Gallic acid calibration'],
    deliverables: ['TPC values (mg GAE/g)', 'Calibration curve'] },
  { name: 'Total Flavonoid Content', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 7,
    description: 'Aluminium chloride colorimetric assay expressed as QE.',
    protocols: ['AlCl3 colorimetric method'],
    deliverables: ['TFC values (mg QE/g)', 'Calibration curve'] },
  { name: 'HPLC', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 14,
    description: 'High-performance liquid chromatography for quantification / fingerprinting.',
    protocols: ['Method development', 'Standard quantification'],
    deliverables: ['Chromatograms', 'Quantification table'] },
  { name: 'GC-MS', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 14,
    description: 'Gas chromatography–mass spectrometry of volatile constituents.',
    protocols: ['Sample derivatisation', 'Library matching'],
    deliverables: ['Compound identification list', 'TIC chromatogram'] },
  { name: 'LC-MS', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 14,
    description: 'Liquid chromatography–mass spectrometry for non-volatile metabolites.',
    protocols: ['LC-MS/MS acquisition', 'Metabolite annotation'],
    deliverables: ['Mass spectra', 'Metabolite table'] },
  { name: 'FTIR', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 5,
    description: 'Fourier-transform infrared spectroscopy for functional group analysis.',
    protocols: ['KBr pellet preparation', 'Spectral acquisition'],
    deliverables: ['FTIR spectra', 'Peak assignment table'] },
  { name: 'UV-Visible Spectroscopy', category: 'Phytochemical & Analytical', icon: 'chart', est_days: 5,
    description: 'UV-Vis absorption spectra and λmax determination.',
    protocols: ['Wavelength scan', 'Quantitative determination'],
    deliverables: ['UV-Vis spectra', 'λmax record'] },

  // ---------- In Vitro Bioassays ----------
  { name: 'Antioxidant Assay (DPPH)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 10,
    description: 'DPPH radical scavenging assay; IC50 determination.',
    protocols: ['DPPH scavenging protocol', 'Ascorbic acid standard'],
    deliverables: ['IC50 values', '% inhibition curve'] },
  { name: 'Antioxidant Assay (ABTS)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 10,
    description: 'ABTS•+ radical cation decolourisation assay.',
    protocols: ['ABTS protocol', 'Trolox standard'],
    deliverables: ['TEAC values', 'IC50'] },
  { name: 'Antioxidant Assay (FRAP)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 7,
    description: 'Ferric reducing antioxidant power assay.',
    protocols: ['FRAP protocol', 'FeSO4 calibration'],
    deliverables: ['FRAP values (μM Fe2+/g)'] },
  { name: 'Antioxidant Assay (Nitric Oxide / H2O2)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 10,
    description: 'Nitric oxide and hydrogen peroxide scavenging assays.',
    protocols: ['NO scavenging', 'H2O2 scavenging'],
    deliverables: ['% scavenging', 'IC50'] },
  { name: 'Antidiabetic Assay (α-Amylase)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 12,
    description: 'α-Amylase inhibition assay; acarbose as standard.',
    protocols: ['DNSA method'],
    deliverables: ['IC50 values', 'Inhibition curve'] },
  { name: 'Antidiabetic Assay (α-Glucosidase)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 12,
    description: 'α-Glucosidase inhibition assay.',
    protocols: ['pNPG substrate method'],
    deliverables: ['IC50 values'] },
  { name: 'Antidiabetic Assay (Glucose Uptake)', category: 'In Vitro Bioassay', icon: 'dish', est_days: 14,
    description: 'Cellular glucose uptake assay (e.g. L6 / 3T3-L1).',
    protocols: ['2-NBDG uptake protocol'],
    deliverables: ['Uptake fold-change data'] },
  { name: 'Anti-inflammatory Assay', category: 'In Vitro Bioassay', icon: 'dish', est_days: 12,
    description: 'Protein denaturation, HRBC membrane stabilisation, COX/LOX inhibition.',
    protocols: ['Protein denaturation', 'HRBC stabilisation', 'COX/LOX inhibition'],
    deliverables: ['% inhibition', 'IC50 values'] },
  { name: 'Anticancer / Cytotoxicity Assay', category: 'In Vitro Bioassay', icon: 'dish', est_days: 21,
    description: 'MTT / SRB cytotoxicity on cell lines (HeLa, MCF-7, A549, HepG2, HT-29, Caco-2, EAC).',
    protocols: ['MTT assay', 'Cell culture maintenance'],
    deliverables: ['IC50 per cell line', 'Dose-response curves'] },
  { name: 'Antimicrobial Assay', category: 'In Vitro Bioassay', icon: 'dish', est_days: 14,
    description: 'Disc diffusion / MIC / MBC against bacterial and fungal strains.',
    protocols: ['Disc diffusion', 'Broth microdilution (MIC/MBC)'],
    deliverables: ['Zone of inhibition table', 'MIC/MBC values'] },

  // ---------- In Vivo / Pharmacology ----------
  { name: 'Acute Toxicity Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 21,
    description: 'OECD 423/425 acute oral toxicity to establish LD50 / safe dose.',
    protocols: ['OECD 425 protocol', 'Ethical clearance'],
    deliverables: ['LD50 / safe dose', 'Observation log'] },
  { name: 'Subacute Toxicity Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 35,
    description: 'OECD 407 repeated-dose 28-day toxicity study.',
    protocols: ['OECD 407 protocol'],
    deliverables: ['Body weight data', 'Organ indices'] },
  { name: 'Chronic Toxicity Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 90,
    description: 'Long-term repeated dose toxicity evaluation.',
    protocols: ['Chronic dosing protocol'],
    deliverables: ['Longitudinal toxicity data'] },
  { name: 'In Vivo Pharmacological Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 45,
    description: 'Disease-model efficacy study in animals.',
    protocols: ['Animal model induction', 'Treatment grouping'],
    deliverables: ['Efficacy data', 'Statistical comparison'] },
  { name: 'Analgesic Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 21,
    description: 'Hot-plate / tail-flick / writhing analgesic models.',
    protocols: ['Acetic acid writhing', 'Hot plate method'],
    deliverables: ['Reaction time / writhing counts'] },
  { name: 'Antipyretic Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 21,
    description: 'Brewer\'s yeast induced pyrexia model.',
    protocols: ['Yeast-induced pyrexia'],
    deliverables: ['Rectal temperature data'] },
  { name: 'Hepatoprotective Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 35,
    description: 'CCl4 / paracetamol induced hepatotoxicity protection.',
    protocols: ['CCl4 induction', 'Liver marker assay'],
    deliverables: ['SGPT/SGOT/ALP data'] },
  { name: 'Neuroprotective Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 40,
    description: 'Behavioural and biochemical neuroprotection assessment.',
    protocols: ['Behavioural testing', 'Oxidative stress markers'],
    deliverables: ['Behavioural scores', 'Brain biochemistry'] },
  { name: 'Cardioprotective Study', category: 'In Vivo & Pharmacology', icon: 'mouse', est_days: 40,
    description: 'Isoproterenol-induced cardiotoxicity protection model.',
    protocols: ['ISO induction', 'Cardiac marker assay'],
    deliverables: ['CK-MB / LDH / troponin data'] },
  { name: 'Histopathology', category: 'In Vivo & Pharmacology', icon: 'microscope', est_days: 21,
    description: 'Tissue sectioning, H&E staining and microscopic grading.',
    protocols: ['Tissue processing', 'H&E staining'],
    deliverables: ['Histology images', 'Grading table'] },
  { name: 'Biochemical Analysis', category: 'In Vivo & Pharmacology', icon: 'chart', est_days: 14,
    description: 'Serum / tissue biochemical parameter estimation.',
    protocols: ['Enzymatic kit assays'],
    deliverables: ['Biochemical parameter table'] },

  // ---------- Computational ----------
  { name: 'Molecular Docking', category: 'Computational', icon: 'cpu', est_days: 21,
    description: 'Protein–ligand docking to predict binding affinity and pose.',
    protocols: ['Protein/ligand preparation', 'Docking (AutoDock Vina)'],
    deliverables: ['Binding energies', 'Docking pose images'] },
  { name: 'Virtual Screening', category: 'Computational', icon: 'cpu', est_days: 21,
    description: 'High-throughput screening of compound libraries against targets.',
    protocols: ['Library preparation', 'Batch docking'],
    deliverables: ['Ranked hit list'] },
  { name: 'ADMET Prediction', category: 'Computational', icon: 'cpu', est_days: 10,
    description: 'Absorption, distribution, metabolism, excretion & toxicity prediction.',
    protocols: ['SwissADME / pkCSM / ADMETlab'],
    deliverables: ['ADMET property table', 'Drug-likeness report'] },
  { name: 'Molecular Dynamics Simulation', category: 'Computational', icon: 'cpu', est_days: 35,
    description: 'MD simulation to assess complex stability (RMSD, RMSF, Rg, H-bonds).',
    protocols: ['System setup', 'Equilibration & production run', 'Trajectory analysis'],
    deliverables: ['RMSD/RMSF plots', 'MM-PBSA energies'] },
  { name: 'Network Pharmacology', category: 'Computational', icon: 'cpu', est_days: 21,
    description: 'Compound–target–disease network and pathway enrichment.',
    protocols: ['Target prediction', 'PPI network', 'Enrichment analysis'],
    deliverables: ['Network diagrams', 'KEGG/GO enrichment'] },
  { name: 'Protein-Ligand Interaction Analysis', category: 'Computational', icon: 'cpu', est_days: 10,
    description: 'Detailed interaction mapping (H-bonds, hydrophobic, π-stacking).',
    protocols: ['Interaction profiling (LigPlot+/Discovery Studio)'],
    deliverables: ['Interaction diagrams', 'Residue contact list'] },

  // ---------- Analysis & Documentation ----------
  { name: 'Statistical Analysis', category: 'Analysis & Documentation', icon: 'chart', est_days: 14,
    description: 'ANOVA / t-test / regression analysis of experimental data.',
    protocols: ['One-way ANOVA', 'Post-hoc tests'],
    deliverables: ['Statistical output', 'Significance tables'] },
  { name: 'Graph Generation', category: 'Analysis & Documentation', icon: 'chart', est_days: 7,
    description: 'Publication-quality figures and graphs (GraphPad/Origin).',
    protocols: ['Figure preparation guidelines'],
    deliverables: ['Final figures'] },
  { name: 'Manuscript Writing', category: 'Analysis & Documentation', icon: 'doc', est_days: 30,
    description: 'Drafting the research manuscript for journal submission.',
    protocols: ['IMRaD structure', 'Journal formatting'],
    deliverables: ['Manuscript draft', 'Figures & tables'] },
  { name: 'Publication Preparation', category: 'Analysis & Documentation', icon: 'doc', est_days: 30,
    description: 'Journal selection, submission and revision handling.',
    protocols: ['Journal selection', 'Cover letter', 'Response to reviewers'],
    deliverables: ['Submission record', 'Acceptance letter'] },
  { name: 'Thesis Writing', category: 'Analysis & Documentation', icon: 'doc', est_days: 60,
    description: 'Compilation of the complete thesis/dissertation.',
    protocols: ['Thesis structure', 'University formatting'],
    deliverables: ['Thesis chapters', 'Final thesis PDF'] },
  { name: 'Final Defense Preparation', category: 'Analysis & Documentation', icon: 'doc', est_days: 21,
    description: 'Defense presentation and viva preparation.',
    protocols: ['Presentation design', 'Mock defense'],
    deliverables: ['Defense slides', 'Anticipated Q&A'] },
];

module.exports = { CATALOG };
